blank_issues_enabled: false
contact_links:
  - name: Questions or Help
    url: https://www.patreon.com/timgonzalez
    about: Join us on Patreon for direct questions and chat
  - name: Quick feedback
    url: https://timgonzalez.itch.io
    about: Leave comments on itch.io pages
  - name: CurseForge
    url: https://www.curseforge.com/
    about: Check the mod pages on CurseForge
